site_name: PETER SOMMER - Technical Blog
site_description: "...Clouds, Server und IT-Wahnsinn"
site_url: https://sommercloud.de
theme:
  name: material
  custom_dir: docs/overrides
  language: de
  icon:
    logo: fontawesome/solid/cloud-sun
  favicon: images/favicon.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - navigation.tracking

    
  font:
    text: Quicksand
    code: Source Code Pro
plugins:
  - blog:
      blog_dir: .
      post_url_format: "{categories}/{slug}"
      archive: false
      post_date_format: long
      post_url_date_format: yyyy
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      authors_file: "{blog}/.authors.yml"
  - search
  - tags
  - privacy
  - rss:
        match_path: "posts/.*"
        date_from_meta:
          as_creation: date.created
          as_update: date.updated
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: auto
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

nav:
  - Blog: index.md
  - Über: about.md


extra:
  consent:
    title: Cookie-Zustimmung
    description: >- 
      Wir verwenden Cookies, um Ihre wiederholten Besuche und Präferenzen zu erkennen sowie die Effektivität unserer Webseite zu messen und zu überprüfen, 
      ob Benutzer das finden, wonach sie suchen. Mit Ihrer Zustimmung helfen Sie uns, unsere Webseite zu verbessern.
    cookies:
      analytics: Microsoft Clarity
    
  analytics: 
    provider: custom
    property: clarity
    
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/peter-sommer-3170a8139/
    - icon: /fontawesome/regular/envelope
      name: Sende mir eine E-Mail
      link: mailto:peter@sommer-email.de
    - icon: fontawesome/solid/rss
      link: https://sommercloud.de/feed_rss_created.xml


  
copyright: >
  &copy; 2024 Peter Sommer –
  <a href="#__consent">Cookie Einstellungen</a>
  

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: "#"
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details

hooks:
  - hooks/socialmedia.py

extra_css:
  - css/extra.css